### ISSUE TITLE
Category Selector on Article Drafts View

### ISSUE THREAD

**Issue by RomanBoegli** [TKone7/lightread#29] opened 2019-12-16 15:56 UTC
Each article must be assigned with a category. Hence, the draft view must provide an appropriate control.

**Comment by TKone7** [comment] 2019-12-17 09:21
Is this duplicate of https://github.com/TKone7/lightread/issues/27? Or what is the difference?

**Comment by RomanBoegli** [comment] 2019-12-17 10:24
You're right, #27 is redundant. I closed it.

**Comment by TKone7** [comment] 2019-12-17 14:20
done with 64b802c5dbd46a61ac67117882056e328f4f8962
Be aware of the database changes that need to be applied.

**Closed** 2019-12-17 14:20 UTC
